[package]
name = "gp"
version = "0.1.0"
authors = ["Chris Kaltwasser <chris@chrisk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sscanf = "0.1.2"
format_num = "0.1.0"
nom = "6.2.1"
