# gpopt_select_method := fpb | tournament
# gpopt_rng := thread | seedable | file_stream
# gpopt_trace := on | off
# gpopt_adf := yes | no
# gpopt_mult_threaded := yes | no
# gpopt_even_parity_k= 3 | 4 | 5 | 6
[build]
rustflags = """
    --cfg gpopt_select_method="tournament"
    --cfg gpopt_rng="thread"
    --cfg gpopt_trace="off"
    --cfg gpopt_mult_threaded="yes"
    --cfg gpopt_adf="yes"
    --cfg gpopt_even_parity_k="3"
"""
