# gpopt_select_method := fpb | tournament
# gpopt_rng := thread | seedable | file_stream
# gpopt_trace := on | off
[build]
rustflags = """
    --cfg gpopt_select_method="tournament"
    --cfg gpopt_rng="seedable"
    --cfg gpopt_trace="off"
"""
