# gpopt_select_method := fpb | tournament
# gpopt_rng := thread | seedable | file_stream
# gpopt_trace := on | off
# gpopt_fitness_type := float | int
# gpopt_exec_criteria := each_fitness_case | clock
[build]
rustflags = """
    --cfg gpopt_select_method="fpb"
    --cfg gpopt_rng="thread"
    --cfg gpopt_trace="off"
    --cfg gpopt_fitness_type="float"
    --cfg gpopt_exec_criteria="each_fitness_case"
"""
