# gpopt_select_method := fpb | tournament
# gpopt_rng := thread | seedable | file_stream
# gpopt_trace := on | off
# gpopt_adf := yes | no
# gpopt_mult_threaded := yes | no
# gpopt_even_parity_k= 7 | 8 | 9 | 10 | 11
[build]
rustflags = """
    --cfg gpopt_select_method="fpb"
    --cfg gpopt_rng="thread"
    --cfg gpopt_trace="off"
    --cfg gpopt_mult_threaded="yes"
    --cfg gpopt_adf="yes"
    --cfg gpopt_even_parity_k="7"
"""
